---


- include_tasks: roles/elasticsearch/tasks/Elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'


- include_tasks: roles/elasticsearch/tasks/Elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'


- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: {{ elasticsearch_host }}'

- name: Updating the port in config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: {{ elasticsearch_port }}'
 
- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: started
